### ISSUE TITLE
Legal status of the last public build

### ISSUE THREAD

**Issue by asiekierka** [Domochevsky/minecraft-quiverbow#6]
Since you've stated that the current build is an incomplete mess, having the source code to the last public version would be handy to compare changes and make fixing bugs easier. Are you in possession of it? If so, could it be uploaded? If not, are we allowed to consider decompiled versions of the last public build to be under the same license as QuiverBow's source code release is now?

**Comment by Daomephsta** [comment]
@asiekierka The source code on the repo is functional as of 2e7c7fe1e974a5e472c6a4f4d8aeb8728cd3d185. 

Models are borked, but everything else works.

**Comment by Domochevsky** [comment]
@asiekierka what they said, pretty much. I do still have the source for b95, if I see this correctly. 
However, if only models are currently busted then fixing those should be sufficient to get this metaphorical deathstar fully operational again. :)
(I think there's even still an option in there to use icons instead of models, to get around that for the time being.)
